liquibase:
  user: homeenv
  password: homeenv
  url: jdbc:postgresql://localhost:5432/homeenv
  change-log: classpath:db/changelog/changelog-master.xml

spring:
  application:
    name: homeenv
  config:
    name: homeenv
  session:
    store-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/homeenv
    username: homeenv
    password: homeenv


security:
  basic:
    enabled: false

homeenv:
  indexing:
    path: "/home/dominator/test"
    recursive: true

eureka:
  client:
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    ROOT: DEBUG
#
