liquibase:
  user: homeenv
  password: homeenv
  url: jdbc:postgresql://localhost:5432/homeenv
  change-log: classpath:db/changelog/changelog-master.xml

spring:
  application:
    name: homeenv
  config:
    name: homeenv
  session:
    store-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/homeenv
    username: homeenv
    password: homeenv
  rabbitmq:
#   user: homeenv
#   password: homeenv
   host: localhost
   port: 5672
#   virtual-host: homeenv


security:
  basic:
    enabled: false

homeenv:
  indexing:
    path: "/home/fox/Pictures/1111"
    recursive: true

  rabbit:
    queueIndexingRequests: indexing_requests
    queueIndexingResponses: indexing_responses
    exchangeName: homeenv

eureka:
  client:
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file: homeenv.log
#  level:
#    ROOT: DEBUG
#
